services:
    web:
        image: node:22.9.0
        volumes:
            - ./app:/usr/src/app
        ports:
            - "82:9000"
        working_dir: /usr/src/app
        command: sh -c "chmod +x rush.sh && ./rush.sh"

        